version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpassword
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=192.168.33.10
      - N8N_PORT=5678
    volumes:
      - ./n8n_data:/home/node/.n8n