version: "3.8"

services:
  tooljet:
    image: tooljet/try:ee-lts-latest
    container_name: tooljet
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - tooljet_data:/var/lib/postgresql/13/main
    platform: linux/amd64

volumes:
  tooljet_data:
